# Generated by Django 4.1.7 on 2023-04-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titele', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TimeField()),
            ],
        ),
    ]
